# frozen_string_literal: true

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

# rubocop:disable Metrics/BlockLength
platform :ios do
  desc 'Build app'
  lane :build do
    gym
  end

  desc 'Run unit tests'
  lane :tests do
    run_tests(scheme: 'statium-ios-swift')
  end

  desc 'Lint code'
  lane :lint do
    swiftlint(
      mode: :lint,
      path: 'statium-ios-swift'
    )
  end

  desc 'Generate new localized screenshots'
  lane :screenshots do
    capture_screenshots(scheme: 'statium-ios-swift-UITests')
  end

  desc 'Manage signing abilities, including devices, certificates, and provisioning profiles'
  lane :manage_signing do
    register_devices(
      devices_file: './devices.txt'
    )
    sync_code_signing(
      force_for_new_devices: true
    )
  end
end
# rubocop:enable Metrics/BlockLength
